### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by fuku1988** [fuku1988/furima-29789#10]
* 自身のフリマアプリのURL | 本番環境(Heroku)のURL
https://furima-29789.herokuapp.com/

* Basic認証のIDとパスワード | 
BASIC_AUTH_PASSWORD: 2525
BASIC_AUTH_USER:            admin

* 出品者用のメールアドレスとパスワード | 本番環境にて商品出品しているユーザーの情報
umeko@sample.com
umeko123

* 購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
suzuki@sample.com
suzuki123

* 購入用カードの番号・期限・セキュリティコード | PAY.JPのテストカード情報
カード番号4242424242424242
期限12月21年
セキュリティコード123

以上、宜しくお願いいたします。

**Comment by tech-oa** [comment]
fuku1988さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○クレジットカード情報は必須であり、正しいクレジットカードの情報で無いときは決済できない
→セキュリティコードが「111」でも購入することができてしまいました。

○URLを直接入力して購入済み商品の購入ページへ遷移しようとすると、トップページに遷移する
→購入ページに遷移してしまいます。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by fuku1988** [comment]
> [修正箇所]
> ○クレジットカード情報は必須であり、正しいクレジットカードの情報で無いときは決> 済できない
> →セキュリティコードが「111」でも購入することができてしまいました。クレジット

クレジットカード情報はテストカードの番号であるため、cvcはどの番号でも購入できてしまうようです。（参考URL: https://pay.jp/docs/testcard）バリデーションの設定でtokenにpresence: trueを付与しているのでおそらくエラーとなるはずですが、以下コードを追記いたしました。（不要であれば削除いたします）

```
    if params[:token].blank?
      redirect_to item_order_path
```

> ○URLを直接入力して購入済み商品の購入ページへ遷移しようとすると、トップページ> に遷移する
> →購入ページに遷移してしまいます。

修正いたしました。

以上、ご確認のほど宜しくお願いいたします。

**Comment by fuku1988** [comment]
@tech-oa さま

コードレビューありがとうございます。

> [修正箇所]
> ○クレジットカード情報は必須であり、正しいクレジットカードの情報で無いときは決> > 済できない
> →セキュリティコードが「111」でも購入することができてしまいました。

クレジットカード情報はテストカードの番号であるため、cvcはどの番号でも購入できてしまうようです。（参考URL: https://pay.jp/docs/testcard）バリデーション設定で　tokenに　presence: true　を付与していますが、以下コードを追記いたしました。しかしテストカードの情報ですので、以下を追記したところでエラーの確認ができませんでした。単体テストコードで挙動の確認いたしました。（こちらの追記コードが不要であれば削除いたします）

```
    if params[:token].blank?
      redirect_to item_order_path
```

> ○URLを直接入力して購入済み商品の購入ページへ遷移しようとすると、トップページ> に遷移する
> →購入ページに遷移してしまいます。

修正いたしました。

以上、ご確認のほど宜しくお願いいたします。

**Comment by tech-oa** [comment]
fuku1988 さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

セキュリティコードの件は、こちらで問題ないと確認をさせていただきました。
大変失礼いたしました。
丁寧に回答していただきまして、有り難うございました。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
